name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Crear y configurar la clave SSH privada
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/ssh_key
          chmod 600 ~/.ssh/ssh_key
          echo -e "Host lau-raspberry-dev.freemyip.com\n\tStrictHostKeyChecking no\n\tIdentityFile ~/.ssh/ssh_key" > ~/.ssh/config

      # 3. Prueba de conexión SSH
      - name: Test SSH Connection
        run: ssh lau@lau-raspberry-dev.freemyip.com "echo 'SSH connection successful'"

      # 4. Ejecutar git pull en la Raspberry Pi
      - name: Deploy updates via git pull
        run: ssh lau@lau-raspberry-dev.freemyip.com "cd /var/www/Sportseek && git pull origin main"
