name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install LFTP
      run: sudo apt-get install -y lftp

    - name: Install PHP and extensions
      run: |
        sudo apt-get update
        sudo apt-get install -y php php-cli php-mbstring php-xml php-mysql

    - name: Install Composer dependencies
      run: |
        if [ -f composer.json ]; then
          composer install
        else
          echo "No composer.json found. Skipping Composer install."
        fi

    - name: Run your PHP script
      run: php bd.php # Reemplaza 'your_script.php' con el nombre de tu script PHP
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    - name: Deploy only changed files via FTP
      run: lftp -c "set ssl:verify-certificate no; open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }}; mirror -R --only-newer . /htdocs"
      env:
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_SERVER: ${{ secrets.FTP_SERVER }}