name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y php php-cli php-mbstring php-xml php-mysql rsync

    - name: Run your PHP script (local test)
      run: php administrador/config/bd.php
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    - name: Deploy files to Raspberry Pi via SSH
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        rsync -avz -e "ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" \
          --exclude '.git' \
          ./ "${{ env.USERNAME }}@${{ env.SERVER_IP }}:/var/www/"

    - name: Execute post-deployment commands on Raspberry Pi
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        ssh -o StrictHostKeyChecking=no "${{ env.USERNAME }}@${{ env.SERVER_IP }}" << 'EOF'
        cd /var/www/
        # Agrega aquí cualquier comando adicional que necesites ejecutar después del despliegue
        sudo systemctl restart nginx
        EOF
