name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y php php-cli php-mbstring php-xml php-mysql lftp

    - name: Set up FTP credentials
      run: |
        echo "set ftp:ssl-allow true" > ~/.lftprc
        echo "set ftp:ssl-force true" >> ~/.lftprc
        echo "set ftp:ssl-protect-data true" >> ~/.lftprc
        echo "set ftp:passive-mode true" >> ~/.lftprc
        echo "open ftp://${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}@${{ secrets.FTP_SERVER }}:${{ secrets.FTP_PORT }}" > deploy_commands.lftp
        echo "mirror -R ./ /var/www/" >> deploy_commands.lftp
        echo "exit" >> deploy_commands.lftp

    - name: Deploy files to Raspberry Pi via FTP
      run: |
        lftp -f deploy_commands.lftp

    - name: Execute post-deployment commands on Raspberry Pi
      run: |
        ssh -o StrictHostKeyChecking=no "${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }}" << 'EOF'
        cd /var/www/
        # Agrega aquí cualquier comando adicional que necesites ejecutar después del despliegue
        sudo systemctl restart nginx
        EOF
