name: Deploy to Raspberry Pi via FTP

on:
  push:
    branches:
      - main  # O la rama que uses para producción

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repositorio
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Instalar lftp para la transferencia FTP
      - name: Install lftp
        run: sudo apt-get install lftp

      # Subir archivos modificados por FTP
      - name: Upload changed files via FTP
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: |
          # Guardar la lista de archivos modificados en el último commit
          FILES=$(git diff --name-only HEAD^ HEAD)

          # Iniciar sesión en el servidor FTP y transferir los archivos
          for file in $FILES; do
            if [ -f "$file" ]; then
              # Transferir solo los archivos que hayan cambiado
              lftp -f "
                open ftp://$FTP_USER:$FTP_PASS@$FTP_HOST
                cd /var/www
                put -O /var/www $file
                bye
              "
            fi
          done
